CREATE TABLE instrument (
    symbol         VARCHAR(20) PRIMARY KEY,   -- e.g. 'EUR/USD', 'BTC/USD', 'AAPL'
    name           VARCHAR(100) NOT NULL,     -- display name, e.g. 'Apple Inc.'
    exchange       VARCHAR(50),               -- e.g. 'NASDAQ' for stocks; NULL for forex/crypto pairs
    type           VARCHAR(30) NOT NULL CHECK (type IN ('forex', 'crypto', 'stock'))  -- the app's three supported asset classes
);
-- NAMING: every identifier in this file is snake_case, never camelCase.
-- Postgres folds unquoted identifiers to lowercase, so a column or function
-- written as `someName` silently becomes `somename` in the actual database, and
-- every later reference would need "someName" in double quotes forever.
-- snake_case avoids that entirely.

CREATE TABLE price_candle (
    symbol      VARCHAR(20) NOT NULL REFERENCES instrument(symbol),
    interval    VARCHAR(10) NOT NULL CHECK (interval IN ('2h', '4h', '1day', '1week')),
    datetime    TIMESTAMP NOT NULL,
    open        NUMERIC(18,5) NOT NULL,
    high        NUMERIC(18,5) NOT NULL,
    low         NUMERIC(18,5) NOT NULL,
    close       NUMERIC(18,5) NOT NULL,
    volume      BIGINT,
    PRIMARY KEY (symbol, interval, datetime)
);
-- Interval strings are fixed to the four the app actually uses, and are spelled
-- the way Twelve Data spells them in its own `interval` request parameter, so the
-- mapping from API response -> stored rows needs no translation.
--
-- The CHECK is deliberate: without it, a single typo ('1d' instead of '1day')
-- inserts happily and then every read for that symbol silently returns zero rows
-- -- which looks exactly like "not ingested yet" and is painful to debug.
--
-- Chart range -> interval: 1w -> 2h, 1m -> 4h, 6m -> 1day, 1yr -> 1week.


-- Every user-scoped feature -- watchlist, demo-trading trades, journal
-- entries -- hangs off this table.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    cash_balance  NUMERIC(18,5) NOT NULL DEFAULT 10000.00 CHECK (cash_balance >= 0),
    created_at    TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
-- Named app_user, not user: `user` is a reserved word in SQL and a built-in
-- function in Postgres (it returns the current role), so an unquoted
-- `CREATE TABLE user` is a syntax error.
--
-- id is a surrogate key, not the username: usernames are the login handle and a
-- user may one day want to change theirs, which would cascade through every
-- row that references them.
--
-- GENERATED BY DEFAULT rather than ALWAYS so an explicit id can still be given
-- in seed data or a test fixture; Hibernate's IDENTITY strategy never supplies
-- one, so both spellings work for the application itself.
--
-- password_hash holds a hash and NEVER a password. There is deliberately no
-- `password` column anywhere in this schema.
--
-- UNIQUE on username is enforced here rather than only by a SELECT-then-INSERT
-- in Java: two concurrent registrations can both pass that check and both
-- insert. The constraint makes the second one fail, which the backend maps to
-- the API's 409. Uniqueness is case-SENSITIVE.
--
-- cash_balance is the virtual demo-trading balance, starting at $10,000
-- -- the default lives here so the rule holds even for a row
-- inserted by hand. NUMERIC(18,5) matches the price columns in price_candle on
-- purpose: cash is debited by price x quantity, and mixing a 5-decimal price
-- with a 2-decimal balance rounds every forex and crypto trade. The
-- CHECK (>= 0) is a backstop only.
--
-- created_at is stored in UTC (NOTE 1 below), like the intraday candles.

-- Each user's personal watchlist. A join table and nothing
-- more -- it says which instruments a user has saved, and when.

CREATE TABLE watchlist (
    user_id  BIGINT      NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    symbol   VARCHAR(20) NOT NULL REFERENCES instrument(symbol),
    added_at TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    PRIMARY KEY (user_id, symbol)
);
-- The composite primary key IS the no-duplicates rule. Adding the same
-- instrument twice is not prevented by application code remembering to check
-- -- it is impossible, because the row already exists.
--
-- It doubles as the index for the query the app actually runs. "Everything on
-- this user's watchlist" filters on user_id, which is the leading column of the
-- key, so Postgres uses the primary key index for it. No second index needed.
--
-- ON DELETE CASCADE on user_id: deleting an account takes its watchlist rows
-- with it.
--
-- Deliberately NO cascade on symbol. The default (NO ACTION) means deleting an
-- instrument that somebody has saved fails with a constraint error, which is
-- the behaviour we want.
--
-- added_at exists so the list has a stable order (oldest first). Stored in UTC
-- like every other timestamp in this schema -- see NOTE 1 below.


-- Simulated trades, CFD-style. One row = one POSITION: opened
-- LONG or SHORT at an entry price, and -- once closed -- the price it closed at.

CREATE TABLE trade (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    symbol      VARCHAR(20)   NOT NULL REFERENCES instrument(symbol),
    direction   VARCHAR(5)    NOT NULL CHECK (direction IN ('LONG', 'SHORT')),
    quantity    NUMERIC(18,8) NOT NULL CHECK (quantity > 0),
    entry_price NUMERIC(18,5) NOT NULL CHECK (entry_price > 0),
    opened_at   TIMESTAMP     NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    exit_price  NUMERIC(18,5)     NULL CHECK (exit_price > 0),
    closed_at   TIMESTAMP         NULL CHECK (closed_at >= opened_at),
    CONSTRAINT trade_closed_atomically CHECK ((exit_price IS NULL) = (closed_at IS NULL))
);

CREATE INDEX idx_trade_user_opened ON trade (user_id, symbol, opened_at DESC);
-- A ROW IS A POSITION, SO THE RESULT IS A PROPERTY OF THE ROW. Buys and sells
-- are never paired with each other: a SHORT is a first-class opening, not the
-- sale of something held. Every trade carries its own entry and exit, and its
-- profit or loss is a pure function of this one row:
--
--     pnl = max( (reference - entry_price) * quantity * sign,  -entry_price * quantity )
--     sign = +1 for LONG, -1 for SHORT
--     reference = exit_price when closed, otherwise the live price
--
-- which is why there is no position table, no pnl column and no total column.
-- Each would be derivable exactly from this row, and a stored copy is one more
-- thing that can disagree.
--
-- THE max() CAPS A LOSS AT THE MARGIN. Opening reserves entry_price * quantity
-- out of app_user.cash_balance (leverage 1:1); closing returns margin + pnl. A
-- LONG can never lose more than its margin, because a price cannot go below
-- zero. A SHORT can -- but only once the price has doubled from entry. Capping
-- it means the credit on close is never negative, so CHECK (cash_balance >= 0)
-- holds by construction rather than by luck, and a beginner's simulator never
-- has to explain a debt.
--
-- A TRADE ROW IS UPDATED EXACTLY ONCE, WHEN IT CLOSES -- the only row in this
-- schema that changes after it is written. The close is a single
--     UPDATE trade SET exit_price = ..., closed_at = ...
--     WHERE id = ... AND user_id = ... AND closed_at IS NULL
-- so a second close (a double click, two tabs) matches no row and writes
-- nothing. It is the database, not a check in Java, that makes a double close
-- impossible, and the same statement is what makes someone else's trade
-- unreachable.
--
-- exit_price and closed_at are set TOGETHER or not at all:
-- trade_closed_atomically makes a half-closed trade unrepresentable. The close
-- is one event, not two columns someone has to remember to set in step.
-- closed_at >= opened_at is the cheap half of the same idea.
--
-- entry_price and exit_price are the prices this position actually opened and
-- closed at, captured by the server at those instants.
--
-- quantity is NUMERIC(18,8) while every money column in this schema is
-- NUMERIC(18,5), and that difference is the point. BTC trades around $76,000, so
-- $100 of it is about 0.0013 BTC. At five decimal places that stores as 0.00132
-- -- the order is rounded before it is even written, and a small enough one
-- rounds to zero. Eight decimals is the crypto convention (one satoshi is 1e-8).
--
-- direction is a VARCHAR with a CHECK rather than a Postgres ENUM, for the same
-- reason price_candle.interval is: a CHECK is one line to change and maps onto a
-- Java enum with no special JDBC handling.
--
-- CHECK (quantity > 0), not >= 0: a zero-quantity trade is not a trade. The
-- price CHECKs are the same guard one level up -- they stop Finnhub's {"c":0}
-- "success" response, or a bug that reads a missing price as zero, from being
-- written as a real fill.
--
-- ON DELETE CASCADE on user_id matches watchlist: deleting an account takes its
-- trades with it, because an orphaned trade points at a user id that no longer
-- exists. No cascade on symbol, also like watchlist -- deleting an instrument
-- somebody has traded should fail loudly rather than silently erase history.
--
-- The index is the one read the application makes: "this user's trades for this
-- symbol, newest first". The history shows that list as it is, and the
-- once-a-second chart poll walks the same list to split open trades (for the
-- margin and the live P&L) from closed ones (for the realised total). The DESC
-- is in the index because that list has no other order.
--
-- opened_at and closed_at are UTC like every other timestamp here (NOTE 1 below).
-- Every ORDER BY on this table breaks ties on id, because two trades can land in
-- the same millisecond and a list must not reorder itself between two reads.


-- The trading journal. One row = one note a user wrote, with
-- an optional link to an instrument and an optional link to one of their own
-- trades.

CREATE TABLE journal_entry (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    body       TEXT        NOT NULL CHECK (length(btrim(body)) > 0),
    symbol     VARCHAR(20)     NULL REFERENCES instrument(symbol),
    trade_id   BIGINT          NULL REFERENCES trade(id),
    created_at TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP       NULL
);

CREATE INDEX idx_journal_user_created ON journal_entry (user_id, created_at DESC);
-- THERE ARE DELIBERATELY NO PRICE OR SIGNAL COLUMNS HERE.
--
-- The reason is the trade link two lines up. A trade row already carries the
-- exact prices and instants it opened and closed at, captured by the server. A
-- snapshot stored beside it would be a SECOND record of the same moment: when
-- two records of one moment disagree there is no way to tell afterwards which
-- was right.
--
-- trade_id has NO cascade -- the default NO ACTION. Deleting a trade that an
-- entry points at fails loudly, exactly like watchlist.symbol and trade.symbol.
--
-- user_id DOES cascade. Deleting an account takes its journal with it, because
-- those entries belong to nobody afterwards.
--
-- symbol and trade_id are BOTH nullable and independent. The common entry --
-- "I keep buying tops, slow down" -- links neither. An entry may name an
-- instrument without a trade (a thought about the market), and the app always
-- fills in symbol when it fills in trade_id, but the DB does not force that.
--
-- body is TEXT, not VARCHAR(n). Postgres stores the two identically, so a
-- length cap would be an arbitrary number nobody can defend. The CHECK on the
-- TRIMMED length is the last line of defence: a body of only spaces is not an
-- entry. The readable 400 comes from
-- JournalService; this is the backstop for anything that reaches the table
-- another way.
--
-- updated_at is NULL until the first edit, and is NOT set equal to created_at
-- on insert. Setting it would look tidier and would destroy the only thing the
-- column is for: you could no longer tell "never edited" from "edited
-- instantly".
--
-- The index is (user_id, created_at DESC) because every read of this table is
-- "my journal, newest first" and that is the entire access pattern. The DESC is
-- in the index rather than left to a sort: the list endpoint has no other
-- ordering.
--
-- created_at and updated_at are UTC like every other timestamp here (NOTE 1).


-- NOTE 1: TIMEZONE CONVENTION -- intraday (2h, 4h) `datetime` values are UTC;
-- 1day and 1week values are the exchange's trading date, with no meaningful time
-- of day. This is guaranteed at ingestion: the Twelve Data request sends
-- timezone=UTC, which that API applies to intraday intervals and ignores for
-- daily/weekly.
