-- UC01: Search instrument — preliminary skeleton only, full model in MS4

CREATE TABLE instrument (
    symbol         VARCHAR(20) PRIMARY KEY,   -- e.g. 'EUR/USD', 'BTC/USD', 'AAPL'
    name           VARCHAR(100) NOT NULL,     -- display name, e.g. 'Apple Inc.'
    exchange       VARCHAR(50),               -- e.g. 'NASDAQ' for stocks; NULL for forex/crypto pairs
    type           VARCHAR(30) NOT NULL CHECK (type IN ('forex', 'crypto', 'stock'))  -- BR1: the app's three supported asset classes
);
-- NAMING: every identifier in this file is snake_case, never camelCase.
-- Postgres folds unquoted identifiers to lowercase, so a column or function
-- written as `someName` silently becomes `somename` in the actual database, and
-- every later reference would need "someName" in double quotes forever.
-- snake_case avoids that entirely, and matches the DB requirements doc.
--
-- REMOVED 2026-09-15: `finnhub_symbol VARCHAR(20)`. It held Finnhub's own
-- spelling of an instrument ('OANDA:EUR_USD', 'BINANCE:BTCUSDT') for the live
-- feed. Demo trading is now BTC/USD only (UC04 BR6), so exactly one Finnhub
-- symbol is ever needed and it lives as a constant in the Java that talks to
-- Finnhub. A column carrying one value for six rows, five of which nothing
-- reads, is not a model of anything. If demo trading ever covers more than one
-- instrument, this column comes back -- along with seed values and the entity
-- field.

CREATE TABLE price_candle (
    symbol      VARCHAR(20) NOT NULL REFERENCES instrument(symbol),
    interval    VARCHAR(10) NOT NULL CHECK (interval IN ('2h', '4h', '1day', '1week')),
    datetime    TIMESTAMP NOT NULL,
    open        NUMERIC(18,5) NOT NULL,
    high        NUMERIC(18,5) NOT NULL,
    low         NUMERIC(18,5) NOT NULL,
    close       NUMERIC(18,5) NOT NULL,
    volume      BIGINT,
    PRIMARY KEY (symbol, interval, datetime)
);
-- Interval strings are fixed to the four the app actually uses, and are spelled
-- the way Twelve Data spells them in its own `interval` request parameter, so the
-- mapping from API response -> stored rows needs no translation.
--
-- The CHECK is deliberate: without it, a single typo ('1d' instead of '1day')
-- inserts happily and then every read for that symbol silently returns zero rows
-- -- which looks exactly like "not ingested yet" and is painful to debug. Drop it
-- if you'd rather keep the column open-ended, but then the four functions below
-- and the ingestion code have to agree on spelling by convention alone.
--
-- Chart range -> interval (SCRUM-61): 1w -> 2h, 1m -> 4h, 6m -> 1day, 1yr -> 1week.


-- UC03/UC04/UC05 (SCRUM-39): accounts. Every user-scoped feature -- watchlist,
-- demo-trading positions and trades, journal entries -- hangs off this table.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    cash_balance  NUMERIC(18,5) NOT NULL DEFAULT 10000.00 CHECK (cash_balance >= 0),
    created_at    TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC')
);
-- Named app_user, not user: `user` is a reserved word in SQL and a built-in
-- function in Postgres (it returns the current role), so an unquoted
-- `CREATE TABLE user` is a syntax error and every later reference would need
-- "user" in double quotes forever -- the same identifier trap as the naming
-- note at the top of this file.
--
-- id is a surrogate key, not the username: usernames are the login handle and a
-- user may one day want to change theirs, which would cascade through every
-- row that references them. Watchlist entries, positions, trades and journal
-- entries (each arriving with its own story) key on this id with
-- REFERENCES app_user(id) ON DELETE CASCADE.
--
-- GENERATED BY DEFAULT rather than ALWAYS so an explicit id can still be given
-- in seed data or a test fixture; Hibernate's IDENTITY strategy never supplies
-- one, so both spellings work for the application itself.
--
-- password_hash holds a hash and NEVER a password. There is deliberately no
-- `password` column anywhere in this schema. A BCrypt hash is exactly 60
-- characters, but Spring Security's DelegatingPasswordEncoder prefixes it with
-- an algorithm tag ("{bcrypt}$2a$10$..."), and swapping the algorithm later
-- would change the length again -- so this is VARCHAR(100), not CHAR(60).
--
-- There is also deliberately no login/verify function in this file. Hashing and
-- verification happen in Java (BCryptPasswordEncoder in the service layer); the
-- database only stores the result. A SQL function that took a plaintext
-- password would put it in the query log and in pg_stat_statements.
--
-- UNIQUE on username is enforced here rather than only by a SELECT-then-INSERT
-- in Java: two concurrent registrations can both pass that check and both
-- insert. The constraint makes the second one fail, which the backend maps to
-- the API's 409. Uniqueness is case-SENSITIVE, so 'Nazir' and 'nazir' are two
-- accounts; if we'd rather they collide, replace UNIQUE with
--   CREATE UNIQUE INDEX app_user_username_lower ON app_user (LOWER(username));
--
-- cash_balance is the virtual demo-trading balance, starting at $10,000
-- (UC04 BR1) -- the default lives here so the rule holds even for a row
-- inserted by hand. NUMERIC(18,5) matches the price columns in price_candle on
-- purpose: cash is debited by price x quantity, and mixing a 5-decimal price
-- with a 2-decimal balance rounds every forex and crypto trade. The
-- CHECK (>= 0) is a backstop only -- "you cannot spend more than you have" is a
-- business rule and belongs in the service layer, where it can produce a
-- readable message instead of a constraint violation.
--
-- created_at is stored in UTC (NOTE 1 below), like the intraday candles.

-- UC03 (SCRUM-22): each user's personal watchlist. A join table and nothing
-- more -- it says which instruments a user has saved, and when.

CREATE TABLE watchlist (
    user_id  BIGINT      NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    symbol   VARCHAR(20) NOT NULL REFERENCES instrument(symbol),
    added_at TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    PRIMARY KEY (user_id, symbol)
);
-- The composite primary key IS the no-duplicates rule (UC03 BR1). Adding the
-- same instrument twice is not prevented by application code remembering to
-- check -- it is impossible, because the row already exists. A surrogate `id`
-- column here would have broken that: every add would be a new, unique row and
-- the duplicate check would live only in Java, where it can be forgotten or
-- lost to a race. There is also nothing that needs to reference a watchlist
-- row, so the surrogate key would buy nothing in exchange.
--
-- It doubles as the index for the query the app actually runs. "Everything on
-- this user's watchlist" filters on user_id, which is the leading column of the
-- key, so Postgres uses the primary key index for it. No second index needed.
--
-- ON DELETE CASCADE on user_id: deleting an account takes its watchlist rows
-- with it. Without it the rows would be orphaned -- pointing at a user id that
-- no longer exists, invisible to every query, and forever.
--
-- Deliberately NO cascade on symbol. The default (NO ACTION) means deleting an
-- instrument that somebody has saved fails with a constraint error, which is
-- the behaviour we want: instruments are reference data ingested from Twelve
-- Data, and one disappearing while users have it saved is a problem to look at,
-- not something to silently clean up.
--
-- added_at exists so the list has a stable order (oldest first). Without it the
-- row order is whatever Postgres feels like, which can change between reads and
-- makes the watchlist appear to shuffle itself. Stored in UTC like every other
-- timestamp in this schema -- see NOTE 1 below.
--
-- No SQL function for adding or reading the list, for the same reason as the
-- rest of this file: the app queries through Spring Data, and the functions
-- here are reference only.


-- UC04 (SCRUM-83): simulated trades, CFD-style. One row = one POSITION: opened
-- LONG or SHORT at an entry price, and -- once closed -- the price it closed at.
-- Replaced the spot model of SCRUM-78 (one row per BUY or SELL execution against
-- a holding) on 2026-09-29.

CREATE TABLE trade (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    symbol      VARCHAR(20)   NOT NULL REFERENCES instrument(symbol),
    direction   VARCHAR(5)    NOT NULL CHECK (direction IN ('LONG', 'SHORT')),
    quantity    NUMERIC(18,8) NOT NULL CHECK (quantity > 0),
    entry_price NUMERIC(18,5) NOT NULL CHECK (entry_price > 0),
    opened_at   TIMESTAMP     NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    exit_price  NUMERIC(18,5)     NULL CHECK (exit_price > 0),
    closed_at   TIMESTAMP         NULL CHECK (closed_at >= opened_at),
    CONSTRAINT trade_closed_atomically CHECK ((exit_price IS NULL) = (closed_at IS NULL))
);

CREATE INDEX idx_trade_user_opened ON trade (user_id, symbol, opened_at DESC);
-- A ROW IS A POSITION, SO THE RESULT IS A PROPERTY OF THE ROW. Buys and sells
-- are never paired with each other: a SHORT is a first-class opening, not the
-- sale of something held. Every trade carries its own entry and exit, and its
-- profit or loss is a pure function of this one row:
--
--     pnl = max( (reference - entry_price) * quantity * sign,  -entry_price * quantity )
--     sign = +1 for LONG, -1 for SHORT
--     reference = exit_price when closed, otherwise the live price
--
-- which is why there is no position table, no pnl column and no total column.
-- Each would be derivable exactly from this row, and a stored copy is one more
-- thing that can disagree -- the rule this schema has now applied four times.
-- get_trade_results() below states the formula in SQL; the application's copy
-- is Trade.pnl in the Java, and the Java is authoritative.
--
-- THE max() CAPS A LOSS AT THE MARGIN. Opening reserves entry_price * quantity
-- out of app_user.cash_balance (leverage 1:1); closing returns margin + pnl. A
-- LONG can never lose more than its margin, because a price cannot go below
-- zero. A SHORT can -- but only once the price has doubled from entry. Capping
-- it means the credit on close is never negative, so CHECK (cash_balance >= 0)
-- holds by construction rather than by luck, and a beginner's simulator never
-- has to explain a debt. The alternative, an automatic margin close-out, would
-- have been code for an event that cannot happen in a demo.
--
-- A TRADE ROW IS UPDATED EXACTLY ONCE, WHEN IT CLOSES -- the only row in this
-- schema that changes after it is written. The close is a single
--     UPDATE trade SET exit_price = ..., closed_at = ...
--     WHERE id = ... AND user_id = ... AND closed_at IS NULL
-- so a second close (a double click, two tabs) matches no row and writes
-- nothing. It is the database, not a check in Java, that makes a double close
-- impossible, and the same statement is what makes someone else's trade
-- unreachable.
--
-- exit_price and closed_at are set TOGETHER or not at all:
-- trade_closed_atomically makes a half-closed trade unrepresentable. The close
-- is one event, not two columns someone has to remember to set in step.
-- closed_at >= opened_at is the cheap half of the same idea.
--
-- entry_price and exit_price are the prices this position actually opened and
-- closed at, captured by the server at those instants. They are the only prices
-- in the application persisted for their own sake: price_candle rows are a cache
-- that can be re-fetched from Twelve Data, and the live chart is a memory window
-- that ages out in half an hour, but "what did I get in at, and out at?" is true
-- only at those instants and no provider can be asked for it later. They are
-- deliberately not foreign keys to price_candle rows: a candle summarises a whole
-- minute, and a fill happens at one instant inside it.
--
-- quantity is NUMERIC(18,8) while every money column in this schema is
-- NUMERIC(18,5), and that difference is the point. BTC trades around $76,000, so
-- $100 of it is about 0.0013 BTC. At five decimal places that stores as 0.00132
-- -- the order is rounded before it is even written, and a small enough one
-- rounds to zero. Eight decimals is the crypto convention (one satoshi is 1e-8).
-- "How precisely can a price be quoted" and "how small a fraction of an asset
-- can be held" are different questions; giving them the same answer only looks
-- tidy.
--
-- direction is a VARCHAR with a CHECK rather than a Postgres ENUM, for the same
-- reason price_candle.interval is: a CHECK is one line to change and maps onto a
-- Java enum with no special JDBC handling.
--
-- CHECK (quantity > 0), not >= 0: a zero-quantity trade is not a trade. The
-- price CHECKs are the same guard one level up -- they stop Finnhub's {"c":0}
-- "success" response, or a bug that reads a missing price as zero, from being
-- written as a real fill.
--
-- ON DELETE CASCADE on user_id matches watchlist: deleting an account takes its
-- trades with it, because an orphaned trade points at a user id that no longer
-- exists. No cascade on symbol, also like watchlist -- deleting an instrument
-- somebody has traded should fail loudly rather than silently erase history.
--
-- The index is the one read the application makes: "this user's trades for this
-- symbol, newest first". The history shows that list as it is, and the
-- once-a-second chart poll walks the same list to split open trades (for the
-- margin and the live P&L) from closed ones (for the realised total). A partial
-- index over the open rows alone was planned and dropped: the poll needs the
-- closed rows too, so nothing would ever have read it. The DESC is in the index
-- because that list has no other order.
--
-- opened_at and closed_at are UTC like every other timestamp here (NOTE 1 below).
-- Every ORDER BY on this table breaks ties on id, because two trades can land in
-- the same millisecond and a list must not reorder itself between two reads.


-- UC05 (SCRUM-81): the trading journal. One row = one note a user wrote, with
-- an optional link to an instrument and an optional link to one of their own
-- trades.

CREATE TABLE journal_entry (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    body       TEXT        NOT NULL CHECK (length(btrim(body)) > 0),
    symbol     VARCHAR(20)     NULL REFERENCES instrument(symbol),
    trade_id   BIGINT          NULL REFERENCES trade(id),
    created_at TIMESTAMP   NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP       NULL
);

CREATE INDEX idx_journal_user_created ON journal_entry (user_id, created_at DESC);
-- THERE ARE DELIBERATELY NO PRICE OR SIGNAL COLUMNS HERE, and the absence is
-- the decision -- which is why it is written down rather than merely not
-- present. UC05 step 6 originally specified that submitting an entry snapshots
-- the instrument's current price and signal at that moment. That was dropped on
-- 2026-09-22, before any of it was built.
--
-- The reason is the trade link two lines up. A trade row already carries the
-- exact prices and instants it opened and closed at, captured by the server. A
-- snapshot stored beside it would be a SECOND record of the same moment, and
-- this schema has refused that every time (no position table, no pnl or total
-- column, one price_candle table): when two records of one moment disagree
-- there is no way to tell afterwards which was right. The only prices stored for
-- their own sake anywhere in this schema are trade.entry_price and
-- trade.exit_price, and their justification is written on that table.
--
-- The cost, stated rather than left to be discovered: an entry that links an
-- instrument but NO trade no longer records what that instrument was worth when
-- it was written. That is accepted. An entry that wants to say "this is what
-- the market was doing" links a trade; an entry that does not is a note, and a
-- note does not need a price.
--
-- trade_id has NO cascade -- the default NO ACTION. Deleting a trade that an
-- entry points at fails loudly, exactly like watchlist.symbol and trade.symbol.
-- Nothing in the application deletes a trade and nothing is planned to; this
-- constraint is what will stop that silently orphaning somebody's writing if it
-- is ever added, and the behaviour can be decided then with the case actually
-- in front of us rather than guessed at now.
--
-- user_id DOES cascade, and the asymmetry is deliberate. Deleting an account
-- takes its journal with it, because those entries belong to nobody afterwards.
-- Deleting a trade is a different question, answered above. Note that an
-- account deletion removes the trades and the entries together, so it cannot
-- produce the orphan case either.
--
-- symbol and trade_id are BOTH nullable and independent. The common entry --
-- "I keep buying tops, slow down" -- links neither. An entry may name an
-- instrument without a trade (a thought about the market), and the app always
-- fills in symbol when it fills in trade_id, but the DB does not force that:
-- a CHECK tying them together would buy nothing and would have to be relaxed
-- the first time a note is attached to a trade whose instrument was renamed.
--
-- body is TEXT, not VARCHAR(n). Postgres stores the two identically, so a
-- length cap would be an arbitrary number nobody can defend, and the failure it
-- creates -- somebody's long entry truncated or rejected -- is worse than a
-- long row. The CHECK on the TRIMMED length is UC05 5a at the last line of
-- defence: a body of only spaces is not an entry. The readable 400 comes from
-- JournalService; this is the backstop for anything that reaches the table
-- another way.
--
-- updated_at is NULL until the first edit, and is NOT set equal to created_at
-- on insert. Setting it would look tidier and would destroy the only thing the
-- column is for: you could no longer tell "never edited" from "edited
-- instantly". Same instinct as app_user.cash_balance keeping five decimals --
-- the tidy-looking choice loses information the feature needs.
--
-- The index is (user_id, created_at DESC) because every read of this table is
-- "my journal, newest first" and that is the entire access pattern. The DESC is
-- in the index rather than left to a sort: the list endpoint has no other
-- ordering and never will, since a journal is read in the order it was written.
--
-- created_at and updated_at are UTC like every other timestamp here (NOTE 1).


-- ============================================================
-- Read functions
--
-- REFERENCE ONLY (2026-08-31): the application does NOT call these. Instrument
-- search, the per-range candle window and the staleness rule are all
-- implemented in Java (InstrumentRepository, PriceRepository, PriceService).
-- These are kept as the DB-side statement of the same rules, and as the smoke
-- tests at the bottom of this file. Two independent implementations of one rule
-- is how SCRUM-52 happened -- if a rule changes, the Java is authoritative.
--
-- Named snake_case rather than camelCase (getInstruments etc. in the
-- requirements doc) for the same reason as the naming note at the top: Postgres
-- lowercases unquoted identifiers, so getInstruments would have to be called
-- as "getInstruments" with quotes forever. Same functions, safer spelling.
-- ============================================================

-- Instrument search (UC01 steps 4-8). Matches the user's input against both
-- symbol and name, case-insensitively, as a substring -- so "eur" finds
-- 'EUR/USD', and "apple" finds 'AAPL'.
--
-- Results are ranked: exact symbol match first, then symbol prefix, then name
-- prefix, then any other substring hit; ties broken alphabetically by name.
--
-- "Not found" signal: an EMPTY RESULT SET, not NULL. This replaces the old
-- search_instrument(), which returned a single symbol or NULL -- that only ever
-- worked because it returned one row. The backend maps an empty set to the REST
-- API's 404 / NOT_FOUND response (see backend/CONTRACTS.md), so the DB signal and
-- the API signal stay in lock-step.
CREATE OR REPLACE FUNCTION get_instruments(p_query VARCHAR)
RETURNS TABLE (
    symbol   VARCHAR(20),
    name     VARCHAR(100),
    type     VARCHAR(30),
    exchange VARCHAR(50)
) AS $$
BEGIN
    RETURN QUERY
    SELECT i.symbol, i.name, i.type, i.exchange
    FROM instrument i
    WHERE i.symbol ILIKE '%' || p_query || '%'
       OR i.name   ILIKE '%' || p_query || '%'
    ORDER BY
        CASE
            WHEN i.symbol ILIKE p_query           THEN 0   -- exact symbol
            WHEN i.symbol ILIKE p_query || '%'    THEN 1   -- symbol starts with
            WHEN i.name   ILIKE p_query || '%'    THEN 2   -- name starts with
            ELSE 3                                          -- substring anywhere
        END,
        i.name;
END;
$$ LANGUAGE plpgsql;

-- Daily candles for the chart (SCRUM-61: the 6m range uses 1day).
--
-- p_limit is "the most recent N candles", NOT the first N ever stored -- a 3m
-- chart wants the last ~90 days, not the 90 oldest rows we happen to have. The
-- inner query takes the newest N (datetime DESC), the outer one flips them back
-- into chronological order, which is what a chart needs to plot left-to-right.
--
-- Returns an empty set if the symbol is unknown or has no daily candles yet;
-- call check_price_data() first if you need to tell those apart from "we have
-- data but it's stale".
CREATE OR REPLACE FUNCTION get_daily_price(p_symbol VARCHAR, p_limit INTEGER)
RETURNS TABLE (
    datetime TIMESTAMP,
    open     NUMERIC(18,5),
    high     NUMERIC(18,5),
    low      NUMERIC(18,5),
    close    NUMERIC(18,5),
    volume   BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT latest.datetime, latest.open, latest.high, latest.low, latest.close, latest.volume
    FROM (
        SELECT c.datetime, c.open, c.high, c.low, c.close, c.volume
        FROM price_candle c
        WHERE c.symbol = p_symbol
          AND c.interval = '1day'
        ORDER BY c.datetime DESC
        LIMIT p_limit
    ) latest
    ORDER BY latest.datetime;
END;
$$ LANGUAGE plpgsql;
-- get_four_hr_price and get_weekly_price are the same body with '4h' / '1week'
-- substituted for '1day' -- left for Glenn per the requirements doc.

-- Reports whether we have usable price data for a symbol at a given interval, so
-- the business logic layer knows whether it needs to trigger ingestion from
-- Twelve Data before showing a chart (UC01 step 10 / extension 10a: "fetches (or
-- reuses cached) current price/chart data... falls back to cached data with an
-- outdated notice, or an error state if nothing is cached").
--
-- Returns one of:
--   'MISSING'      -> zero rows for this symbol+interval: nothing to show,
--                      a full fetch is needed.
--   'INSUFFICIENT' -> some rows exist, but either too few to plot a meaningful
--                      chart (< min_candles) or the newest candle is older than
--                      that interval's own staleness threshold (we're missing at
--                      least the most recent candle).
--   'OK'           -> enough recent data, serve straight from cache.
--
-- MISSING and INSUFFICIENT both mean "call ingestion" as far as the caller is
-- concerned -- they're only split out so ingestion/logging can tell "nothing at
-- all" apart from "have something, but it's stale or too thin".
--
-- Now takes p_interval, since price_candle holds all four intervals: asking
-- "do we have data for EUR/USD" is meaningless without saying at which interval.
-- An unknown interval raises rather than returning a value, so a typo surfaces
-- immediately instead of masquerading as MISSING.
--
-- NOTE 1: TIMEZONE CONVENTION -- intraday (2h, 4h) `datetime` values are UTC;
-- 1day and 1week values are the exchange's trading date, with no meaningful time
-- of day. This is guaranteed at ingestion: the Twelve Data request sends
-- timezone=UTC, which that API applies to intraday intervals and ignores for
-- daily/weekly. It is NOT an assumption -- it was one until 2026-09-08, and it
-- was wrong: the parameter defaults to "Exchange", so candles were arriving on
-- each instrument's own exchange clock. NOW() here is timestamptz and is
-- compared via the session's timezone setting; the Java side does the same
-- comparison explicitly in UTC (PriceService.needsIngestion).
--
-- NOTE 2: the staleness threshold is exactly one interval, which is strict.
-- Forex and stock markets close on weekends, so on a Sunday the newest 4h candle
-- is legitimately hours old and this reports INSUFFICIENT, triggering an
-- ingestion call that finds nothing new. If that turns into wasted Twelve Data
-- requests against the 800/day cap, widen the thresholds (e.g. 1.5x the interval)
-- or make them market-hours aware.
--
-- CORRECTED 2026-09-21: the Java side did exactly that -- Interval
-- .stalenessThreshold() has been 1.5x the candle length since the range
-- switcher landed. This function was left at 1x, and '2h' was missing from the
-- CASE above entirely (added 2026-09-21), so calling it for the 1w range raised
-- "Unknown interval" while the price_candle CHECK accepted 2h rows happily.
-- Nothing broke, because nothing calls this -- which is the REFERENCE ONLY
-- banner earning its keep, and also the exact drift it warns about. The Java is
-- authoritative; this function is now correct about the interval set and still
-- deliberately stricter about staleness.
DROP FUNCTION IF EXISTS check_price_data(VARCHAR);  -- the old 1-arg version; CREATE OR REPLACE
                                                    -- below would otherwise ADD an overload
                                                    -- rather than replace it, leaving both live
CREATE OR REPLACE FUNCTION check_price_data(p_symbol VARCHAR, p_interval VARCHAR)
RETURNS VARCHAR AS $$
DECLARE
    row_count            INTEGER;
    latest_dt            TIMESTAMP;
    staleness_threshold  INTERVAL;
    min_candles          CONSTANT INTEGER := 2;
BEGIN
    staleness_threshold := CASE p_interval
        WHEN '2h'    THEN INTERVAL '2 hours'
        WHEN '4h'    THEN INTERVAL '4 hours'
        WHEN '1day'  THEN INTERVAL '1 day'
        WHEN '1week' THEN INTERVAL '7 days'
    END;

    IF staleness_threshold IS NULL THEN
        RAISE EXCEPTION 'Unknown interval: %. Expected one of 2h, 4h, 1day, 1week.', p_interval;
    END IF;

    SELECT COUNT(*), MAX(c.datetime) INTO row_count, latest_dt
    FROM price_candle c
    WHERE c.symbol = p_symbol
      AND c.interval = p_interval;

    IF row_count = 0 THEN
        RETURN 'MISSING';
    ELSIF row_count < min_candles OR latest_dt < (NOW() - staleness_threshold) THEN
        RETURN 'INSUFFICIENT';
    ELSE
        RETURN 'OK';
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Every trade for one user with its result (UC04). REFERENCE ONLY, like
-- everything in this section -- the application computes the result in Java
-- (Trade.pnl), which is authoritative.
--
-- This is the SQL statement of the one formula in the trade table's comment:
-- the capped profit or loss against the exit price. An OPEN trade has no exit
-- price, so its result here is NULL -- not zero. Its live result needs the
-- current market price, which lives in the application's memory, not in this
-- database; the API values open trades against the chart's price instead.
CREATE OR REPLACE FUNCTION get_trade_results(p_user_id BIGINT)
RETURNS TABLE (
    id          BIGINT,
    direction   VARCHAR(5),
    quantity    NUMERIC,
    entry_price NUMERIC,
    exit_price  NUMERIC,
    opened_at   TIMESTAMP,
    closed_at   TIMESTAMP,
    pnl         NUMERIC
) AS $$
BEGIN
    RETURN QUERY
    SELECT t.id,
           t.direction,
           t.quantity,
           t.entry_price,
           t.exit_price,
           t.opened_at,
           t.closed_at,
           CASE WHEN t.exit_price IS NULL THEN NULL
                ELSE ROUND(GREATEST(
                         (t.exit_price - t.entry_price) * t.quantity
                             * CASE t.direction WHEN 'LONG' THEN 1 ELSE -1 END,
                         -(t.entry_price * t.quantity)
                     ), 5)
           END
    FROM trade t
    WHERE t.user_id = p_user_id
    ORDER BY t.opened_at DESC, t.id DESC;
END;
$$ LANGUAGE plpgsql;


-- One user's journal, newest first (UC05 steps 8-9). REFERENCE ONLY: the
-- application reads this through JournalRepository, not through here.
--
-- The parameter is the user id and there is no variant without it. That is the
-- point of the function rather than an oversight: an entry id is a small
-- integer and therefore guessable, so every read of this table in the
-- application is scoped by owner IN THE QUERY -- findByIdAndUserId, never
-- findById followed by a comparison in Java. The second shape reads somebody
-- else's row into memory first, which is one careless log line away from
-- leaking it, and it invites a later refactor to drop the check. This function
-- is written the same way so the DB-side statement of the rule does not quietly
-- disagree with the Java one.
--
-- symbol and trade_id come back as they are stored, including NULL. The join to
-- instrument or trade is the caller's business; resolving it here would make
-- this function a second implementation of what JournalService already does.
CREATE OR REPLACE FUNCTION get_journal(p_user_id BIGINT)
RETURNS TABLE (
    id         BIGINT,
    body       TEXT,
    symbol     VARCHAR(20),
    trade_id   BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
) AS $$
BEGIN
    RETURN QUERY
    SELECT j.id,
           j.body,
           j.symbol,
           j.trade_id,
           j.created_at,
           j.updated_at
    FROM journal_entry j
    WHERE j.user_id = p_user_id
    ORDER BY j.created_at DESC, j.id DESC;
END;
$$ LANGUAGE plpgsql;
-- ORDER BY breaks ties on id for the same reason the trade queries do: two
-- entries written in the same millisecond must still come back in a stable
-- order, or the list appears to shuffle between two identical reads.


-- ============================================================
-- Manual smoke test (run by hand in psql once the container is up)
-- ============================================================
-- INSERT INTO instrument (symbol, name, exchange, type)
--   VALUES ('EUR/USD', 'Euro / US Dollar', NULL, 'forex');
-- INSERT INTO instrument (symbol, name, exchange, type)
--   VALUES ('AAPL', 'Apple Inc.', 'NASDAQ', 'stock');
-- INSERT INTO instrument (symbol, name, exchange, type)
--   VALUES ('BTC/USD', 'Bitcoin / US Dollar', NULL, 'crypto');
-- INSERT INTO price_candle (symbol, interval, datetime, open, high, low, close, volume)
--   VALUES ('EUR/USD', '1day', '2026-08-22 00:00:00', 1.0800, 1.0820, 1.0790, 1.0810, NULL);
--
-- SELECT * FROM get_instruments('EUR/USD');       -- exact symbol match -> one row, EUR/USD
-- SELECT * FROM get_instruments('apple');         -- case-insensitive name match -> AAPL
-- SELECT * FROM get_instruments('doesnotexist');  -- expect: 0 rows (the "not found" signal)
--
-- SELECT * FROM get_daily_price('EUR/USD', 30);   -- expect: the 1 candle above
-- SELECT * FROM get_daily_price('AAPL', 30);      -- expect: 0 rows
--
-- SELECT check_price_data('BTC/USD', '1day');     -- expect: 'MISSING' (zero rows)
-- SELECT check_price_data('EUR/USD', '1day');     -- expect: 'INSUFFICIENT' (1 old candle)
-- SELECT check_price_data('EUR/USD', '4h');       -- expect: 'MISSING' (no 4h rows)
-- SELECT check_price_data('EUR/USD', 'banana');   -- expect: ERROR, unknown interval
--
-- INSERT INTO app_user (username, password_hash)
--   VALUES ('demo', '{bcrypt}$2a$10$notARealHashJustForTheSmokeTest......................');
-- SELECT username, cash_balance FROM app_user;     -- expect: demo, 10000.00000 (the default)
-- INSERT INTO app_user (username, password_hash)
--   VALUES ('demo', 'whatever');                   -- expect: ERROR, duplicate key (username is UNIQUE)
-- UPDATE app_user SET cash_balance = -1 WHERE username = 'demo';
--                                                  -- expect: ERROR, violates check constraint
--
-- INSERT INTO watchlist (user_id, symbol)
--   VALUES ((SELECT id FROM app_user WHERE username = 'demo'), 'EUR/USD');
-- INSERT INTO watchlist (user_id, symbol)
--   VALUES ((SELECT id FROM app_user WHERE username = 'demo'), 'EUR/USD');
--                                                  -- expect: ERROR, duplicate key (UC03 BR1)
-- SELECT symbol, added_at FROM watchlist;          -- expect: one row, EUR/USD
-- DELETE FROM app_user WHERE username = 'demo';
-- SELECT count(*) FROM watchlist;                  -- expect: 0 (ON DELETE CASCADE)
--
-- UC04 trades (SCRUM-83). Assumes BTC/USD above.
-- INSERT INTO app_user (username, password_hash) VALUES ('trader', 'x');
-- INSERT INTO trade (user_id, symbol, direction, quantity, entry_price)
--   VALUES ((SELECT id FROM app_user WHERE username='trader'), 'BTC/USD', 'LONG', 0.00100000, 76000.00000);
-- INSERT INTO trade (user_id, symbol, direction, quantity, entry_price)
--   VALUES ((SELECT id FROM app_user WHERE username='trader'), 'BTC/USD', 'SHORT', 0.00100000, 76000.00000);
-- UPDATE trade SET exit_price = 78000, closed_at = NOW() AT TIME ZONE 'UTC'
--   WHERE direction = 'LONG' AND closed_at IS NULL;
-- UPDATE trade SET exit_price = 78000, closed_at = NOW() AT TIME ZONE 'UTC'
--   WHERE direction = 'SHORT' AND closed_at IS NULL;
-- SELECT direction, pnl FROM get_trade_results((SELECT id FROM app_user WHERE username='trader'));
--                                        -- expect: SHORT -2.00000, LONG 2.00000 (same move, opposite sign)
-- UPDATE trade SET exit_price = 1, closed_at = NOW() AT TIME ZONE 'UTC'
--   WHERE direction = 'LONG' AND closed_at IS NULL;
--                                        -- expect: UPDATE 0 -- already closed; a second close writes nothing
-- INSERT INTO trade (user_id, symbol, direction, quantity, entry_price, exit_price, closed_at)
--   VALUES ((SELECT id FROM app_user WHERE username='trader'), 'BTC/USD', 'SHORT', 0.00100000, 76000, 200000,
--           NOW() AT TIME ZONE 'UTC');
-- SELECT pnl FROM get_trade_results((SELECT id FROM app_user WHERE username='trader')) LIMIT 1;
--                                        -- expect: -76.00000 -- a short above 2x entry is capped at the margin
-- INSERT INTO trade (user_id, symbol, direction, quantity, entry_price)
--   VALUES ((SELECT id FROM app_user WHERE username='trader'), 'BTC/USD', 'LONG', 0.001, 76000);
-- SELECT pnl FROM get_trade_results((SELECT id FROM app_user WHERE username='trader')) LIMIT 1;
--                                        -- expect: NULL -- an open trade has no result in the database
-- INSERT INTO trade (user_id, symbol, direction, quantity, entry_price, exit_price)
--   VALUES ((SELECT id FROM app_user WHERE username='trader'), 'BTC/USD', 'LONG', 1, 76000, 77000);
--                                        -- expect: ERROR, trade_closed_atomically (exit price but no close time)
-- INSERT INTO trade (user_id, symbol, direction, quantity, entry_price)
--   VALUES ((SELECT id FROM app_user WHERE username='trader'), 'BTC/USD', 'HOLD', 1, 76000);
--                                        -- expect: ERROR, violates check constraint (direction LONG/SHORT)
-- INSERT INTO trade (user_id, symbol, direction, quantity, entry_price)
--   VALUES ((SELECT id FROM app_user WHERE username='trader'), 'BTC/USD', 'LONG', 0, 76000);
--                                        -- expect: ERROR, violates check constraint (quantity > 0)
-- INSERT INTO trade (user_id, symbol, direction, quantity, entry_price)
--   VALUES ((SELECT id FROM app_user WHERE username='trader'), 'BTC/USD', 'LONG', 1, 0);
--                                        -- expect: ERROR, violates check constraint (entry_price > 0)
--
-- UC05 journal (SCRUM-81). Continues with the 'trader' user and trades above.
-- INSERT INTO journal_entry (user_id, body)
--   VALUES ((SELECT id FROM app_user WHERE username='trader'), 'Bought too early again.');
-- INSERT INTO journal_entry (user_id, body, symbol, trade_id)
--   VALUES ((SELECT id FROM app_user WHERE username='trader'), 'Sized this one properly.', 'BTC/USD',
--           (SELECT id FROM trade WHERE user_id = (SELECT id FROM app_user WHERE username='trader') LIMIT 1));
-- SELECT * FROM get_journal((SELECT id FROM app_user WHERE username='trader'));
--                                        -- expect: 2 rows, newest first; the first has NULL symbol and trade_id
-- INSERT INTO journal_entry (user_id, body)
--   VALUES ((SELECT id FROM app_user WHERE username='trader'), '    ');
--                                        -- expect: ERROR, violates check constraint (body is blank once trimmed)
-- INSERT INTO journal_entry (user_id, body, symbol)
--   VALUES ((SELECT id FROM app_user WHERE username='trader'), 'note', 'NOPE/USD');
--                                        -- expect: ERROR, foreign key (no such instrument)
-- DELETE FROM trade WHERE user_id = (SELECT id FROM app_user WHERE username='trader');
--                                        -- expect: ERROR, foreign key -- a journal entry points at one of these
--                                        --         rows and NO ACTION refuses rather than orphaning it
-- SELECT updated_at FROM journal_entry LIMIT 1;    -- expect: NULL (never edited)
-- DELETE FROM app_user WHERE username = 'trader';
-- SELECT count(*) FROM journal_entry;    -- expect: 0 (ON DELETE CASCADE, trades and entries together)
